import os
import requests
import base64
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME")
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}


def create_repo(repo_name: str) -> str:
    """Create a new GitHub repo. Returns repo URL."""
    # Delete repo if it already exists (for demo reruns)
    requests.delete(
        f"https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}",
        headers=HEADERS
    )

    res = requests.post(
        "https://api.github.com/user/repos",
        headers=HEADERS,
        json={
            "name": repo_name,
            "description": "Generated by AI Builder",
            "private": False,
            "auto_init": True
        }
    )
    res.raise_for_status()
    return res.json()["html_url"]


def push_files(repo_name: str, files: dict) -> bool:
    """Push all generated files to the repo."""
    import time
    time.sleep(2)  # Wait for repo init

    for file_path, content in files.items():
        encoded = base64.b64encode(content.encode()).decode()

        # Check if file exists (to get SHA for update)
        check = requests.get(
            f"https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}/contents/{file_path}",
            headers=HEADERS
        )

        payload = {
            "message": f"Add {file_path}",
            "content": encoded
        }
        if check.status_code == 200:
            payload["sha"] = check.json()["sha"]

        res = requests.put(
            f"https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}/contents/{file_path}",
            headers=HEADERS,
            json=payload
        )
        res.raise_for_status()

    return True